FROM continuumio/miniconda3:4.6.14

WORKDIR /usr/src/app

COPY text_categorizer/environment.yml /usr/src/app/text_categorizer/environment.yml

RUN apt-get update --fix-missing && \
    apt-get install -y gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN conda env create --file /usr/src/app/text_categorizer/environment.yml

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["source activate text-categorizer && exec pytest --cov-report html --cov=text_categorizer /usr/src/app/tests/"]
