name: text-categorizer
channels:
- pytorch
dependencies:
- pytorch==1.0.1
- torchvision==0.2.2
- cudatoolkit==10.0.130
- pip==19.1.1
- perl==5.26.2.*
- python==3.7.6
- pip:
  - pandas==0.24.1
  - xlrd==1.2.0
  - nltk==3.4
  - profilehooks==1.10.0
  - numpy==1.16.1
  - scikit-learn==0.20.3
  - tqdm==4.31.1
  - Flask==1.0.2
  - Flask-HTTPAuth==3.2.4
  - imbalanced-learn==0.4.3
  - flair==0.4.1
  - pytest-cov==2.7.1
  - openpyxl==3.0.3
  - https://github.com/MSeal/cython_hunspell/archive/0ac159ff3bfde05d4920e89ac7fba3f8b1b989da.zip
  - mosestokenizer==1.1.0
  - gevent==20.5.0
  # Specific sub-dependencies:
  - sentencepiece==0.1.91
  - greenlet==0.4.16
  - gensim==3.8.3
  - scipy==1.5.2
  - itsdangerous==1.1.0
