name: text-categorizer
channels:
- pytorch
dependencies:
- pytorch==1.0.1
- torchvision==0.2.2
- cudatoolkit==10.0.130
- pip==19.1.1
- pip:
  - pandas==0.24.1
  - xlrd==1.2.0
  - nltk==3.4
  - profilehooks==1.10.0
  - numpy==1.16.1
  - scikit-learn==0.20.3
  - stanfordnlp==0.1.2
  - tqdm==4.31.1
  - Flask==1.0.2
  - Flask-HTTPAuth==3.2.4 
  - imblearn==0.0
  - flair==0.4.1
  - pytest-cov==2.7.1
  - xlsxwriter==1.2.1
  - https://github.com/MSeal/cython_hunspell/archive/0ac159ff3bfde05d4920e89ac7fba3f8b1b989da.zip
